prepare:
	git pull
	bundle install --without=development,test
	RAILS_ENV=production rake db:migrate

server:
	RAILS_ENV=production rails s

up:
	test -f tmp/pids/puma || bundle exec puma -e production -p 3000 --pidfile tmp/pids/puma

restart:
	kill -SIGUSR2 `cat tmp/pids/puma`

.PHONY: prepare server