pumapid=tmp/pids/puma
puma=bundle exec puma -e production -p 3000 --pidfile ${pumapid}

prepare:
	git pull
	bundle install --without=development,test
	RAILS_ENV=production rake db:migrate

up:
	test -f ${pumapid} || ${puma}

restart:
	(test -f ${pumapid} && kill -SIGUSR2 `cat ${pumapid}`) || ${puma}

.PHONY: prepare server